APPLICATION_ENV: development

BUGSNAG_JAVASCRIPT_KEY:
BUGSNAG_RUBY_KEY:

MAIL_FROM_DEFAULT_ADDRESS:
MAIL_FROM_DEFAULT_NAME:

OSUNY_STAGING_APP_NAME:
OSUNY_STAGING_PG_ADDON_ID:

OTP_SECRET_ENCRYPTION_KEY:

SCALEWAY_OS_ACCESS_KEY_ID:
SCALEWAY_OS_BUCKET:
SCALEWAY_OS_ENDPOINT:
SCALEWAY_OS_REGION:
SCALEWAY_OS_SECRET_ACCESS_KEY:

SECRET_KEY_BASE:

SEND_IN_BLUE_API_KEY:

SMTP_USER:
SMTP_PASSWORD:

UNSPLASH_ACCESS_KEY:
UNSPLASH_SECRET:

# Pour les tests automatisés
TEST_GITHUB_BRANCH:
TEST_GITHUB_ENDPOINT: '' # no use for github
TEST_GITHUB_TOKEN:
TEST_GITHUB_REPOSITORY:

TEST_GITLAB_BRANCH:
TEST_GITLAB_ENDPOINT:
TEST_GITLAB_TOKEN:
TEST_GITLAB_REPOSITORY:
