default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("OSUNY_DEVELOPMENT_DBNAME", "osuny_development") %>

test:
  <<: *default
  database: osuny_test

production:
  <<: *default
  database: osuny_production
  username: osuny
  password: <%= ENV['OSUNY_DATABASE_PASSWORD'] %>
